
import '@litejs/cli/test.js'
import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { mime, serveAssets } from '../index.mjs'


describe('serveAssets', () => {
	var files = {
		'index.html': '<h1>Home</h1>',
		'app.js': 'console.log(1)',
		'mod.mjs': 'export var x = 1',
		'img/pixel.png': new Uint8Array([ 137, 80, 78, 71 ]),
		'blob.bin': 'raw',
	}
	, assets = serveAssets(files)
	, get = path => assets.fetch(new Request('http://localhost/' + path))

	test('serve a bundled file {0}', [
		[ '', mime.html, '<h1>Home</h1>' ],
		[ 'index.html', mime.html, '<h1>Home</h1>' ],
		[ 'app.js?ts', mime.js, 'console.log(1)' ],
		[ 'mod.mjs', mime.js, 'export var x = 1' ],
		[ 'img/pixel%2Epng', mime.png, '�PNG' ],
	], async (file, type, body, assert) => {
		var res = await get(file)
		assert.equal(res.status, 200)
		assert.equal(res.headers.get('content-type'), type)
		assert.equal(await res.text(), body)
	})

	test('serve 404', async assert => {
		assert.equal(await get('nope'), 404)
		assert.equal(await get('index.htm'), 404)
		assert.equal(await get('index.htmll'), 404)
	})

	test('custom defaultMime/notFound', async assert => {
		var assets = serveAssets(files, { defaultMime: 'text/plain', notFound: () => 'gone' })
		, get = path => assets.fetch(new Request('http://localhost/' + path))
		, res = await get('blob.bin')

		assert.equal(res.status, 200)
		assert.equal(res.headers.get('content-type'), 'text/plain')
		assert.equal(await res.text(), 'raw')

		assert.equal(await get('nope'), 'gone')
	})
})

describe('lj-assets', () => {
	test('prints an import map for public/, walking subdirectories', assert => {
		var cwd = mkdtempSync(join(tmpdir(), 'litejs-assets-'))
		mkdirSync(join(cwd, 'public/sub'), { recursive: true })
		writeFileSync(join(cwd, 'public/a.html'), '')
		writeFileSync(join(cwd, 'public/sub/b.js'), '')
		try {
			var out = execFileSync(process.execPath, [ join(import.meta.dirname, '../lib/bin/lj-assets.mjs') ], { cwd, encoding: 'utf8' })
			assert.equal(out, [
				'// Generated by lj-assets from public/',
				'',
				"import a0 from './public/a.html'",
				"import a1 from './public/sub/b.js'",
				'',
				'export var files = {',
				"\t'a.html': a0,",
				"\t'sub/b.js': a1",
				'}',
				'',
			].join('\n'))
		} finally {
			rmSync(cwd, { recursive: true })
		}
		assert.end()
	})
})

