
import '@litejs/cli/test.js'
import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { mime, serveAssets } from '../index.mjs'

var files = {
	'/index.html': '<h1>Home</h1>',
	'/app.js': 'console.log(1)',
	'/img/pixel.png': new Uint8Array([ 137, 80, 78, 71 ]),
	'/blob.bin': 'raw',
}
, get = (assets, path) => assets.fetch(new Request('http://localhost' + path))

describe('serveAssets', () => {
	test('serves a bundled file with its mime type', async assert => {
		var res = await get(serveAssets(files), '/app.js')
		assert.equal(res.status, 200)
		assert.equal(res.headers.get('content-type'), mime.js)
		assert.equal(await res.text(), 'console.log(1)')
	})

	test('maps / to /index.html', async assert => {
		var res = await get(serveAssets(files), '/')
		assert.equal(res.status, 200)
		assert.equal(res.headers.get('content-type'), mime.html)
		assert.equal(await res.text(), '<h1>Home</h1>')
	})

	test('serves bytes as given and decodes the path', async assert => {
		var res = await get(serveAssets(files), '/img/pixel%2Epng')
		assert.equal(res.headers.get('content-type'), mime.png)
		assert.equal(new Uint8Array(await res.arrayBuffer()), files['/img/pixel.png'])
	})

	test('unknown extensions get defaultMime', async assert => {
		assert.equal((await get(serveAssets(files), '/blob.bin')).headers.get('content-type'), 'application/octet-stream')
		assert.equal((await get(serveAssets(files, { defaultMime: 'text/plain' }), '/blob.bin')).headers.get('content-type'), 'text/plain')
	})

	test('a miss is notFound, 404 by default', async assert => {
		assert.equal(await get(serveAssets(files), '/nope'), 404, 'a bare 404 for toHandler() to shape')
		assert.equal(await get(serveAssets(files, { notFound: () => 'gone' }), '/nope'), 'gone')
	})
})

describe('lj-assets', () => {
	test('prints an import map for public/, walking subdirectories', assert => {
		var cwd = mkdtempSync(join(tmpdir(), 'litejs-assets-'))
		mkdirSync(join(cwd, 'public/sub'), { recursive: true })
		writeFileSync(join(cwd, 'public/a.html'), '')
		writeFileSync(join(cwd, 'public/sub/b.js'), '')
		try {
			var out = execFileSync(process.execPath, [ join(import.meta.dirname, '../lib/bin/lj-assets.mjs') ], { cwd, encoding: 'utf8' })
			assert.equal(out, [
				'// Generated by lj-assets from public/',
				'',
				"import a0 from './public/a.html'",
				"import a1 from './public/sub/b.js'",
				'',
				'export var files = {',
				"\t'/a.html': a0,",
				"\t'/sub/b.js': a1",
				'}',
				'',
			].join('\n'))
		} finally {
			rmSync(cwd, { recursive: true })
		}
		assert.end()
	})
})

