// Generated by lj-assets from public/

import a0 from './public/frame.html'
import a1 from './public/hello.html'
import a2 from './public/index.html'
import a3 from './public/sw.js'
import a4 from './public/test.html'
import a5 from './public/test.js'
import a6 from './public/ui-test.html'

export var files = {
	'/frame.html': a0,
	'/hello.html': a1,
	'/index.html': a2,
	'/sw.js': a3,
	'/test.html': a4,
	'/test.js': a5,
	'/ui-test.html': a6
}
